repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.20.1'
    hooks:
      - id: eslint
        args: [--fix]
        files: \.(ts)$
        types: [file]
        additional_dependencies:
          - eslint@^9.20.1
          - globals@^15.15.0
          - neostandard@^0.11.9
          - typescript@^5.7.3
          - typescript-eslint@^8.24.0
          - eslint-plugin-simple-import-sort@^12.1.1
          - '@typescript-eslint/parser@^8.24.0'
          - '@stylistic/eslint-plugin@^4.0.0'