repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.23.0'
    hooks:
      - id: eslint
        args: [--fix]
        files: \.(ts)$
        types: [file]
        additional_dependencies:
          - '@eslint/js@^9.23.0'
          - eslint@^9.23.0
          - globals@^15.15.0
          - neostandard@^0.11.9
          - typescript@^5.7.3
          - typescript-eslint@^8.28.0
          - eslint-plugin-simple-import-sort@^12.1.1
          - '@typescript-eslint/parser@^8.28.0'
