name: Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build"]
    types: [completed]

permissions:
  contents: write
  id-token: write

jobs:
  check-release:
    runs-on: ubuntu-latest
    outputs:
      should_release: ${{ env.SHOULD_RELEASE }}
    steps:
      - name: 检查是否需要进行版本更新
        id: check
        env:
            LATEST_COMMIT_MESSAGE: ${{ github.event.workflow_run.head_commit.message }}
        run: |
          if [[ "$LATEST_COMMIT_MESSAGE" =~ ^release:\ 发布版本.* ]]; then
              echo "SHOULD_RELEASE=true" >> $GITHUB_ENV
          else
              echo "SHOULD_RELEASE=false" >> $GITHUB_ENV
          fi

  push-tag:
    needs: [check-release]
    if: needs.check-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 pnpm
        uses: pnpm/action-setup@v4

      - name: 提取版本号
        id: extract_version
        run: |
          VERSION=$(pnpm pkg get version | tr -d '"')
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: 推送Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          VERSION="${{ steps.extract_version.outputs.version }}"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"

  create-release:
    needs: [push-tag]
    if: needs.check-release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: build

      - name: 获取变更内容
        id: extract_changelog
        run: |
          CHANGELOG=$(awk 'BEGIN {flag=0}
            /^## / {if (flag) exit; flag=1}
            flag {print}' CHANGELOG.md)
          
          echo "changelog<<EOF" >> "$GITHUB_OUTPUT"
          echo "$CHANGELOG" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"
      
      - name: 构建产物
        run: |
          zip -r build.zip . -x "*.git/*"

      - name: 创建 Release 并上传产物
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.push-tag.outputs.version }}"
          name: "v${{ needs.push-tag.outputs.version }}"
          body: |
            ### 发布说明
            ${{ steps.extract_changelog.outputs.changelog }}
          files: build.zip
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: [push-tag]
    if: needs.check-release.outputs.should_release == 'true'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          ref: build
          
      - name: 设置 pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: |
            - args: [--global, husky]

      - name: 发布到 NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://registry.npmjs.org/
          access: public
          provenance: true